// biome-ignore-all lint: generated-file
/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Link = {
  _type: "link";
  linkType?: "href" | "page" | "post";
  href?: string;
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  openInNewTab?: boolean;
};

export type ImageText = {
  _type: "imageText";
  heading: string;
  subheading?: string;
  content?: BlockContent;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imagePosition?: "left" | "right";
  link?: Link;
  buttonText?: string;
};

export type FeaturesGrid = {
  _type: "featuresGrid";
  heading?: string;
  subheading?: string;
  features?: Array<{
    icon?: string;
    title: string;
    description: string;
    _key: string;
  }>;
};

export type CallToAction = {
  _type: "callToAction";
  heading: string;
  text?: string;
  buttonText?: string;
  link?: Link;
};

export type InfoSection = {
  _type: "infoSection";
  heading?: string;
  subheading?: string;
  content?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "href" | "page" | "post";
    href?: string;
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroTitle: string;
  heroTitleHighlight?: string;
  heroDescription: string;
  heroPrimaryAction?: {
    text?: string;
    href?: string;
  };
  heroSecondaryAction?: {
    text?: string;
    href?: string;
  };
  heroPill?: {
    text?: string;
    href?: string;
  };
  showPostsSection?: boolean;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & CallToAction)
    | ({
        _key: string;
      } & InfoSection)
    | ({
        _key: string;
      } & FeaturesGrid)
    | ({
        _key: string;
      } & ImageText)
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  heroTitle?: string;
  heroDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  heading: string;
  subheading?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & CallToAction)
    | ({
        _key: string;
      } & InfoSection)
    | ({
        _key: string;
      } & FeaturesGrid)
    | ({
        _key: string;
      } & ImageText)
  >;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body?: BlockContent;
  summary?: string;
  relatedImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishDate?: string;
  updatedDate?: string;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  tags?: Array<string>;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  featured?: boolean;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  username: string;
  firstName: string;
  lastName: string;
  slug: Slug;
  bio?: BlockContent;
  headshotImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Link
  | ImageText
  | FeaturesGrid
  | CallToAction
  | InfoSection
  | BlockContent
  | Category
  | Slug
  | Home
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  heroTitle?: string;
  heroDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
} | null;
// Variable: homeQuery
// Query: *[_type == "home" && _id == "homePage"][0]{    _id,    _type,    title,    heroTitle,    heroTitleHighlight,    heroDescription,    heroPrimaryAction,    heroSecondaryAction,    heroPill,    showPostsSection,    "pageBuilder": pageBuilder[]{      ...,      _type == "imageText" => {        ...,        "image": image{          ...,          asset->        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type HomeQueryResult = {
  _id: string;
  _type: "home";
  title: string;
  heroTitle: string;
  heroTitleHighlight: string | null;
  heroDescription: string;
  heroPrimaryAction: {
    text?: string;
    href?: string;
  } | null;
  heroSecondaryAction: {
    text?: string;
    href?: string;
  } | null;
  heroPill: {
    text?: string;
    href?: string;
  } | null;
  showPostsSection: boolean | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "callToAction";
        heading: string;
        text?: string;
        buttonText?: string;
        link?: Link;
      }
    | {
        _key: string;
        _type: "featuresGrid";
        heading?: string;
        subheading?: string;
        features?: Array<{
          icon?: string;
          title: string;
          description: string;
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "imageText";
        heading: string;
        subheading?: string;
        content?: BlockContent;
        image: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        } | null;
        imagePosition?: "left" | "right";
        link?: Link;
        buttonText?: string;
      }
    | {
        _key: string;
        _type: "infoSection";
        heading?: string;
        subheading?: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs: Array<{
            linkType?: "href" | "page" | "post";
            href?: string;
            page: string | null;
            post: string | null;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  > | null;
} | null;
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {          link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      },      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string;
  _type: "page";
  name: string;
  slug: Slug;
  heading: string;
  subheading: string | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "callToAction";
        heading: string;
        text?: string;
        buttonText?: string;
        link: {
          _type: "link";
          linkType?: "href" | "page" | "post";
          href?: string;
          page: string | null;
          post: string | null;
          openInNewTab?: boolean;
        } | null;
      }
    | {
        _key: string;
        _type: "featuresGrid";
        heading?: string;
        subheading?: string;
        features?: Array<{
          icon?: string;
          title: string;
          description: string;
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "imageText";
        heading: string;
        subheading?: string;
        content?: BlockContent;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        imagePosition?: "left" | "right";
        link?: Link;
        buttonText?: string;
      }
    | {
        _key: string;
        _type: "infoSection";
        heading?: string;
        subheading?: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs: Array<{
            linkType?: "href" | "page" | "post";
            href?: string;
            page: string | null;
            post: string | null;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  > | null;
} | null;
// Variable: sitemapData
// Query: *[(_type == "page" || _type == "post") && defined(slug.current) && !(_id in path("drafts.**"))] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string;
      _type: "page";
      _updatedAt: string;
    }
  | {
      slug: string;
      _type: "post";
      _updatedAt: string;
    }
>;
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current) && !(_id in path("drafts.**"))] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": summary,  "coverImage": relatedImage,  "date": coalesce(publishDate, _updatedAt),  "author": author->{    username,    firstName,    lastName,    "picture": headshotImage  },  tags,  categories[]->{    title,    "slug": slug.current  },  featured,  }
export type AllPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    username: string;
    firstName: string;
    lastName: string;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  };
  tags: Array<string> | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featured: boolean | null;
}>;
// Variable: filteredPostsQuery
// Query: *[_type == "post"    && defined(slug.current)    && !(_id in path("drafts.**"))    && (!defined($tag) || $tag in tags)    && (!defined($featured) || featured == $featured)  ] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": summary,  "coverImage": relatedImage,  "date": coalesce(publishDate, _updatedAt),  "author": author->{    username,    firstName,    lastName,    "picture": headshotImage  },  tags,  categories[]->{    title,    "slug": slug.current  },  featured,  }
export type FilteredPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    username: string;
    firstName: string;
    lastName: string;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  };
  tags: Array<string> | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featured: boolean | null;
}>;
// Variable: paginatedPostsQuery
// Query: *[_type == "post"    && defined(slug.current)    && !(_id in path("drafts.**"))    && (!defined($tag) || $tag in tags)    && (!defined($featured) || featured == $featured)  ] | order(date desc, _updatedAt desc) [$start...$end] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": summary,  "coverImage": relatedImage,  "date": coalesce(publishDate, _updatedAt),  "author": author->{    username,    firstName,    lastName,    "picture": headshotImage  },  tags,  categories[]->{    title,    "slug": slug.current  },  featured,  }
export type PaginatedPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    username: string;
    firstName: string;
    lastName: string;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  };
  tags: Array<string> | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featured: boolean | null;
}>;
// Variable: postCountQuery
// Query: count(*[_type == "post"    && defined(slug.current)    && !(_id in path("drafts.**"))    && (!defined($tag) || $tag in tags)    && (!defined($featured) || featured == $featured)  ])
export type PostCountQueryResult = number;
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current) && !(_id in path("drafts.**"))] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": summary,  "coverImage": relatedImage,  "date": coalesce(publishDate, _updatedAt),  "author": author->{    username,    firstName,    lastName,    "picture": headshotImage  },  tags,  categories[]->{    title,    "slug": slug.current  },  featured,  }
export type MorePostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    username: string;
    firstName: string;
    lastName: string;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  };
  tags: Array<string> | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featured: boolean | null;
}>;
// Variable: allTagsQuery
// Query: array::unique(*[_type == "post" && !(_id in path("drafts.**")) && defined(tags)].tags[])
export type AllTagsQueryResult = Array<string | null>;
// Variable: allAuthorsQuery
// Query: *[_type == "person"] | order(username asc) {    _id,    username,    firstName,    lastName,    slug,    "headshotUrl": headshotImage.asset->url  }
export type AllAuthorsQueryResult = Array<{
  _id: string;
  username: string;
  firstName: string;
  lastName: string;
  slug: Slug;
  headshotUrl: string | null;
}>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug && !(_id in path("drafts.**"))] [0] {    "content": body[]{      ...,      markDefs[]{        ...,          _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": summary,  "coverImage": relatedImage,  "date": coalesce(publishDate, _updatedAt),  "author": author->{    username,    firstName,    lastName,    "picture": headshotImage  },  tags,  categories[]->{    title,    "slug": slug.current  },  featured,  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page: string | null;
      post: string | null;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    username: string;
    firstName: string;
    lastName: string;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  };
  tags: Array<string> | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featured: boolean | null;
} | null;
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current) && !(_id in path("drafts.**"))]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string;
}>;
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult;
    '\n  *[_type == "home" && _id == "homePage"][0]{\n    _id,\n    _type,\n    title,\n    heroTitle,\n    heroTitleHighlight,\n    heroDescription,\n    heroPrimaryAction,\n    heroSecondaryAction,\n    heroPill,\n    showPostsSection,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "imageText" => {\n        ...,\n        "image": image{\n          ...,\n          asset->\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': HomeQueryResult;
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n,\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult;
    '\n  *[(_type == "page" || _type == "post") && defined(slug.current) && !(_id in path("drafts.**"))] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult;
    '\n  *[_type == "post" && defined(slug.current) && !(_id in path("drafts.**"))] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": summary,\n  "coverImage": relatedImage,\n  "date": coalesce(publishDate, _updatedAt),\n  "author": author->{\n    username,\n    firstName,\n    lastName,\n    "picture": headshotImage\n  },\n  tags,\n  categories[]->{\n    title,\n    "slug": slug.current\n  },\n  featured,\n\n  }\n': AllPostsQueryResult;
    '\n  *[_type == "post"\n    && defined(slug.current)\n    && !(_id in path("drafts.**"))\n    && (!defined($tag) || $tag in tags)\n    && (!defined($featured) || featured == $featured)\n  ] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": summary,\n  "coverImage": relatedImage,\n  "date": coalesce(publishDate, _updatedAt),\n  "author": author->{\n    username,\n    firstName,\n    lastName,\n    "picture": headshotImage\n  },\n  tags,\n  categories[]->{\n    title,\n    "slug": slug.current\n  },\n  featured,\n\n  }\n': FilteredPostsQueryResult;
    '\n  *[_type == "post"\n    && defined(slug.current)\n    && !(_id in path("drafts.**"))\n    && (!defined($tag) || $tag in tags)\n    && (!defined($featured) || featured == $featured)\n  ] | order(date desc, _updatedAt desc) [$start...$end] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": summary,\n  "coverImage": relatedImage,\n  "date": coalesce(publishDate, _updatedAt),\n  "author": author->{\n    username,\n    firstName,\n    lastName,\n    "picture": headshotImage\n  },\n  tags,\n  categories[]->{\n    title,\n    "slug": slug.current\n  },\n  featured,\n\n  }\n': PaginatedPostsQueryResult;
    '\n  count(*[_type == "post"\n    && defined(slug.current)\n    && !(_id in path("drafts.**"))\n    && (!defined($tag) || $tag in tags)\n    && (!defined($featured) || featured == $featured)\n  ])\n': PostCountQueryResult;
    '\n  *[_type == "post" && _id != $skip && defined(slug.current) && !(_id in path("drafts.**"))] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": summary,\n  "coverImage": relatedImage,\n  "date": coalesce(publishDate, _updatedAt),\n  "author": author->{\n    username,\n    firstName,\n    lastName,\n    "picture": headshotImage\n  },\n  tags,\n  categories[]->{\n    title,\n    "slug": slug.current\n  },\n  featured,\n\n  }\n': MorePostsQueryResult;
    '\n  array::unique(*[_type == "post" && !(_id in path("drafts.**")) && defined(tags)].tags[])\n': AllTagsQueryResult;
    '\n  *[_type == "person"] | order(username asc) {\n    _id,\n    username,\n    firstName,\n    lastName,\n    slug,\n    "headshotUrl": headshotImage.asset->url\n  }\n': AllAuthorsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug && !(_id in path("drafts.**"))] [0] {\n    "content": body[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n    },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": summary,\n  "coverImage": relatedImage,\n  "date": coalesce(publishDate, _updatedAt),\n  "author": author->{\n    username,\n    firstName,\n    lastName,\n    "picture": headshotImage\n  },\n  tags,\n  categories[]->{\n    title,\n    "slug": slug.current\n  },\n  featured,\n\n  }\n': PostQueryResult;
    '\n  *[_type == "post" && defined(slug.current) && !(_id in path("drafts.**"))]\n  {"slug": slug.current}\n': PostPagesSlugsResult;
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult;
  }
}
